version: '3.8'

services:
  jekyll-dev:
    build: .
    ports:
      - "4000:4000"      # Jekyll server
      - "35729:35729"    # LiveReload
    volumes:
      - .:/app
      - /app/vendor      # Excluir vendor bundle del volumen
      - /app/node_modules # Excluir node_modules del volumen
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload --livereload-port 35729 