data:

  - name: QR
    url: https://apps.apple.com/us/app/qr/id6745213752
    description: Scan any QR code instantly and create your own custom codes. The fastest and most intuitive QR scanner you'll ever use.
    subtitle: Code Reader Scanner Generator
    icon: /assets/img/QR/qr-app-icon.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    rating: 4.8
    ratings: 125
    legal:
      option:
        - name: Privacy Policy
          url: https://qrcodereaderapp.lilucat.com/legal/privacy
        - name: Terms of Service
          url: https://qrcodereaderapp.lilucat.com/legal/terms
    # page: qr

  - name: App Lock
    url: https://apps.apple.com/app/apple-store/id6448239603?pt=126142472&ct=fromWebsite&mt=8
    description: Keep your private apps safe and hidden. Lock any app with a password and protect your sensitive information from prying eyes.
    subtitle: Password for Apps, Hide, Block
    icon: /assets/img/applock/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    rating: 4.6
    ratings: 3000
    legal:
      option:
        - name: Privacy Policy
          url: https://applock.lilucat.com/legal/privacy
        - name: Terms of Service
          url: https://applock.lilucat.com/legal/terms
    page: app-lock

  - name: QR Code Reader
    url: https://apps.apple.com/app/apple-store/id6469319539?pt=126142472&ct=fromWebsite&mt=8
    description: Scan QR codes, barcodes, and create your own. Works with WiFi, contacts, calendar events, and more. Your all-in-one QR solution.
    subtitle: Barcodes Scanner & Maker
    icon: /assets/img/qr-code-reader/qr-code-reader-app-icon.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    rating: 4.4
    ratings: 103
    legal:
      option:
        - name: Privacy Policy
          url: https://qrcode.lilucat.com/legal/privacy
        - name: Terms of Service
          url: https://qrcode.lilucat.com/legal/terms
    page: qr-code-reader

  - name: Storage Cleaner
    url: https://apps.apple.com/us/app/storage-cleaner/id6455376072
    description: Running out of space? Clean up your device easily with smart AI that finds duplicates, blurry photos, and unnecessary files.
    subtitle: Free Up Space, Clean Up Photos
    icon: /assets/img/storage-cleaner/storage-cleaner-app-icon.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    rating: 4.4
    ratings: 205
    legal:
      option:
        - name: Privacy Policy
          url: https://storagecleaner.lilucat.com/legal/privacy
        - name: Terms of Service
          url: https://storagecleaner.lilucat.com/legal/terms
    # page: storage-cleaner

  - name: Clean Up iPhone
    url: https://apps.apple.com/us/app/clean-up-iphone/id6738309812
    description: Free up space and boost your device performance. Our AI finds junk files and cleans them up automatically.
    subtitle: Phone Cleaner Free Up Storage
    icon: /assets/img/clean-up-iphone/clean-up-iphone-app-icon.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    rating: 4.6
    ratings: 102
    legal:
      option:
        - name: Privacy Policy
          url: https://cleanmeup.lilucat.com/legal/privacy
        - name: Terms of Service
          url: https://cleanmeup.lilucat.com/legal/terms
    # page: clean-up-iphone

  - name: Photo Vault X
    url: https://apps.apple.com/us/app/photo-vault-x/id6618155410
    description: Keep your precious photos and videos safe with password protection. Hide sensitive memories and lock apps for ultimate privacy.
    subtitle: App Lock, hide videos & pic
    icon: /assets/img/photo-vault-x/photo-vault-x-app-icon.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    rating: 4.4
    ratings: 59
    legal:
      option:
        - name: Privacy Policy
          url: https://photovault.lilucat.com/legal/privacy
        - name: Terms of Service
          url: https://photovault.lilucat.com/legal/terms
    # page: photo-vault-x