data:
  - name: App Lock
    url: https://apps.apple.com/app/id6448239603?pt=126142472&ct=fromWebsite&mt=8
    description: App Lock is a privacy app designed to help keep your sensitive apps hidden and secure. With App Lock, you can easily lock and hide any app you want, ensuring that you remain private and out of sight from prying eyes.
    icon: /assets/img/applock/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    rating: 4.6
    ratings: 380
    legal:
      option:
        - name: Privacy Policy
          url: https://applock.lilucat.com/legal/privacy
        - name: Terms Of Use
          url: https://applock.lilucat.com/legal/terms

  - name: AI PDF Scanner
    url: https://apps.apple.com/app/id6448180124?pt=126142472&ct=fromWebsite&mt=8
    description: With AI PDF Scanner, you can effortlessly comprehend textbooks, handouts, and presentations in no time. But that's not all. AI PDF Scanner also helps you efficiently analyze all types of documents - from financial and sales reports to project and business proposals, invoices, slides and legal contracts. With AI PDF Scanner, you can quickly access the information you need, saving you valuable time and effort.
    icon: /assets/img/aipdfscanner/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg
    rating: 5.0
    ratings: 20
    legal:
      option:
        - name: Privacy Policy
          url: https://aipdf.lilucat.com/legal/privacy
        - name: Terms Of Use
          url: https://aipdf.lilucat.com/legal/terms

  - name: AI Math Solver
    url: https://apps.apple.com/app/apple-store/id6449217479?pt=126142472&ct=fromWebsite&mt=8
    description: The ultimate app for solving all your math problems with ease! Whether you're a student struggling with homework or just someone who wants to sharpen their math skills, our app is here to help you.
    icon: /assets/img/aimath/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    rating: 4.4
    ratings: 31
    legal:
      option:
        - name: Privacy Policy
          url: https://mathsolver.lilucat.com/legal/privacy
        - name: Terms Of Use
          url: https://mathsolver.lilucat.com/legal/terms

  - name: Screenfree
    url: https://apps.apple.com/app/apple-store/id6449741551?pt=126142472&ct=fromWebsite&mt=8
    description: Screenfree is the ultimate solution to help you regain control over your digital life and reduce screen time. With Screenfree, you can break free from the addictive grip of your devices and cultivate healthier habits, allowing you to reclaim your time and focus on what truly matters.
    icon: /assets/img/screenfree/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    rating: 5.0
    ratings: 10
    legal:
      option:
        - name: Privacy Policy
          url: https://screenfree.lilucat.com/legal/privacy
        - name: Terms Of Use
          url: https://screenfree.lilucat.com/legal/terms