data:
  - name: AI Chat
    url: https://apps.apple.com/app/id6447686784
    description: AI Chat by LiluCat. The ultimate AI-powered chat assistant to satisfy all your needs! Say goodbye to tedious web searches and hello to instantaneous solutions with this innovative app.
    icon: /assets/img/aichat/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg
    legal:
      option:
        - name: Privacy Policy
          url: https://chat.lilucat.com/legal/privacy
        - name: Terms Of Use
          url: https://chat.lilucat.com/legal/terms

  - name: App Lock
    url: https://apps.apple.com/app/id6446116245
    description: App Lock is a privacy app designed to help keep your sensitive apps hidden and secure. With App Lock, you can easily lock and hide any app you want, ensuring that you remain private and out of sight from prying eyes.
    icon: /assets/img/applock/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    legal:
      option:
        - name: Privacy Policy
          url: https://applock.lilucat.com/legal/privacy
        - name: Terms Of Use
          url: https://applock.lilucat.com/legal/terms