data:
  - name: App Lock
    url: https://apps.apple.com/app/id6448239603
    description: App Lock is a privacy app designed to help keep your sensitive apps hidden and secure. With App Lock, you can easily lock and hide any app you want, ensuring that you remain private and out of sight from prying eyes.
    icon: /assets/img/applock/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    rating: 4.6
    ratings: 78
    legal:
      option:
        - name: Privacy Policy
          url: https://applock.lilucat.com/legal/privacy
        - name: Terms Of Use
          url: https://applock.lilucat.com/legal/terms

  - name: AI PDF Scanner
    url: https://apps.apple.com/app/id6448180124
    description: With AI PDF Scanner, you can effortlessly comprehend textbooks, handouts, and presentations in no time. But that's not all. AI PDF Scanner also helps you efficiently analyze all types of documents - from financial and sales reports to project and business proposals, invoices, slides and legal contracts. With AI PDF Scanner, you can quickly access the information you need, saving you valuable time and effort.
    icon: /assets/img/aipdfscanner/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg
    rating: 5.0
    ratings: 20
    legal:
      option:
        - name: Privacy Policy
          url: https://aipdf.lilucat.com/legal/privacy
        - name: Terms Of Use
          url: https://aipdf.lilucat.com/legal/terms

  - name: AI Math Solver
    url: https://apps.apple.com/app/apple-store/id6449217479?pt=126142472&ct=GoogleAds&mt=8
    description: The ultimate app for solving all your math problems with ease! Whether you're a student struggling with homework or just someone who wants to sharpen their math skills, our app is here to help you.
    icon: /assets/img/aimath/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    rating: 4.4
    ratings: 31
    legal:
      option:
        - name: Privacy Policy
          url: https://mathsolver.lilucat.com/legal/privacy
        - name: Terms Of Use
          url: https://mathsolver.lilucat.com/legal/terms