data:
  - name: App Lock
    url: https://apps.apple.com/app/id6448239603
    description: App Lock is a privacy app designed to help keep your sensitive apps hidden and secure. With App Lock, you can easily lock and hide any app you want, ensuring that you remain private and out of sight from prying eyes.
    icon: /assets/img/applock/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    legal:
      option:
        - name: Privacy Policy
          url: https://applock.lilucat.com/legal/privacy
        - name: Terms Of Use
          url: https://applock.lilucat.com/legal/terms

  - name: AI PDF Scanner
    url: https://apps.apple.com/app/id6448180124
    description: With AI PDF Scanner, you can effortlessly comprehend textbooks, handouts, and presentations in no time. But that's not all. AI PDF Scanner also helps you efficiently analyze all types of documents - from financial and sales reports to project and business proposals, invoices, slides and legal contracts. With AI PDF Scanner, you can quickly access the information you need, saving you valuable time and effort.
    icon: /assets/img/aipdfscanner/Icon-1024.png
    badge: https://one-badge.com/b/apple/appstore.svg 
    legal:
      option:
        - name: Privacy Policy
          url: https://aipdf.lilucat.com/legal/privacy
        - name: Terms Of Use
          url: https://aipdf.lilucat.com/legal/terms